version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "8080:8080"
  frontend:
    container_name: frontend
    environment:
      - API_HOST_SERVER_SIDE=backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend