CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  group_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  date DATETIME NOT NULL,
  timestamp DATETIME,
  FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE
);