import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Sidebar from "@/components/sidebar/sidebar";
import { WebSocketProvider } from "./WebSocketProvider";
import { CheckSession } from "../middleware";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Social Network",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({ children }) {
  const authed = await CheckSession();
  return (
    <html lang="en">
      <body>
        {authed ? (
          <>
            <WebSocketProvider>
              <Header />
              <aside><Sidebar /></aside>
              <main className={inter.className} style={{ marginLeft: "200px" }}>
                {children}
              </main>
              <div id="chatBox"></div>
            </WebSocketProvider>
          </>
        ) : (
          <>
            <Header />
            <main className={inter.className}>{children}</main>
          </>
        )}
      </body>
    </html>
  );
}
